/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;
import java.util.Random;

import static org.junit.Assert.*;

public class AppTest {

    @Test public void testRecentQuotes() throws FileNotFoundException {
        Gson gson = new Gson();

        Reader reader = new FileReader("./src/main/resources/recentquotes.json");

        JsonFileLines[] quoteObj = gson.fromJson(reader, JsonFileLines[].class);

        Random r = new Random();
        int rand = r.nextInt(quoteObj.length);

//        System.out.println(quoteObj[rand].equals(quoteObj[rand]));


        assertTrue("an error occurred with the Json file",quoteObj[rand].equals(quoteObj[rand]) );

    }



    @Test public void testQuotesFile() throws FileNotFoundException {
        Gson gson = new Gson();

        Reader reader = new FileReader("./src/main/resources/recentquotes.json");

        JsonFileLines[] quoteObj = gson.fromJson(reader, JsonFileLines[].class);

        // Random r = new Random();
        // int rand = r.nextInt(quoteObj.length);






        assertTrue("an error occurred with the Json file", quoteObj.length > 0);

    }
    


}
