/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;
import java.util.Random;

import static org.junit.Assert.*;

public class AppTest {

    @Test public void testRecentQuotes() throws FileNotFoundException {
        Gson gson = new Gson();

        Reader reader = new FileReader("./src/main/resources/recentquotes.json");

        RecentQuotes[] quoteObj = gson.fromJson(reader, RecentQuotes[].class);

        Random r = new Random();
        int rand = r.nextInt(quoteObj.length)+1;

//        System.out.println(quoteObj[rand].equals(quoteObj[rand]));


        assertTrue("an error occurred with the Json file",quoteObj[rand].equals(quoteObj[rand]) );

    }


}
